@AuthComet.Mails_HostAddress = https://localhost:7215

### Send test email
POST {{AuthComet.Mails_HostAddress}}/api/emailtest/send
Content-Type: application/json

{
  "to": "selvinmedina0016@gmail.com",
  "subject": "Test Email Subject",
  "body": "<h1>This is a test email body</h1>",
  "isBodyHtml": true
}

###
