@AuthComet_HostAddress = http://localhost:5218

POST {{AuthComet_HostAddress}}/api/users
Content-Type: application/json

{
  "username": "newUser2",
  "password": "userPassword1234",
  "email": "newuserr@example.com"
}

###